apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-rabbit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-rabbit
  template:
    metadata:
      labels:
        app: inventario-rabbit
    spec:
      containers:
      - name: inventario-rabbit
        image: rabbitmq:3-management
        resources:
          requests:  
            memory: "1000M"
          limits:
            cpu: "1"
            memory: "1000M"  
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbit_user
        - name: RABBITMQ_DEFAULT_PASS
          value: b5x26z4p
