apiVersion: v1
kind: Service
metadata:
  name: inventario-mongo2-service
spec:
  selector:
    app: inventario-api-mongo2
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30004
  type: LoadBalancer  
