apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-api
spec:
  replicas: 1
  selector:
    matchLabels:
      role: inventario-api
  template:
    metadata:
      labels:
        role: inventario-api
    spec:
      containers:
      - name: inventario-api
        image: nestorgacr/inventario:latest
        ports:
          - containerPort: 8086
        env:
          - name: RABBIT_URI
            value: "amqp://rabbit_user:b5x26z4p@192.168.65.3:30002"
          - name: MONGO_URI
            value: "mongodb://192.168.65.3:30001/"