apiVersion: v1
kind: Service
metadata:
  name: inventario-mongo-service
spec:
  selector:
    app: inventario-api-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001
  type: LoadBalancer  
