apiVersion: v1
kind: Service
metadata:
  name: inventario-rabbit-service
spec:
  selector:
    app: inventario-rabbit
  ports:
    - name: rabbitmq-port
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30002
    - name: rabbitmq-management-port
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30003
  type: LoadBalancer

