apiVersion: v1
kind: Service
metadata:
  name: inventario-service
spec:
  selector:
    role: inventario-api
  ports:
    - name: app-port
      port: 8086
      targetPort: 8086
      nodePort: 30000
  type: LoadBalancer

     